[package]
name = "dioxus-desktop"
description = "An example for Dioxus desktop integration."
version = "0.4.0"
rust-version = "1.75"
edition = "2021"
publish = false

[dependencies]
dioxus = "0.5.0"
dioxus-router = "0.5.0"
tracing = "0.1.40"

[dependencies.dioxus-free-icons]
version = "0.8.3"
features = [
    "bootstrap",
    "font-awesome-brands",
    "font-awesome-solid",
    "octicons",
]

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[dependencies.zino]
path = "../../zino"
version = "0.20.1"
features = ["dioxus-desktop", "orm"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.21.1"
features = ["env-filter", "orm-sqlite", "tls-rustls"]

[dependencies.zino-model]
path = "../../zino-model"
version = "0.18.1"

[dependencies.zino-dioxus]
path = "../../zino-dioxus"
version = "0.4.0"
