[package]
name = "ntex-app"
description = "An example for ntex integration."
version = "0.2.2"
rust-version = "1.76"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1.40"

[dependencies.ntex]
version = "2.0.2"
default-features = false

[dependencies.serde]
version = "1.0.204"
features = ["derive"]

[dependencies.zino]
path = "../../zino"
version = "0.23.2"
features = [
    "i18n",
    "jwt",
    "ntex",
    "orm",
]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.24.2"
features = [
    "cookie",
    "env-filter",
    "orm-postgres",
    "view-minijinja",
]

[dependencies.zino-derive]
path = "../../zino-derive"
version = "0.21.2"

[dependencies.zino-model]
path = "../../zino-model"
version = "0.21.2"
