[package]
name = "axum-app"
description = "An example for axum integration."
version = "0.13.0"
rust-version = "1.75"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1.40"

[dependencies.axum]
version = "0.6.20"
default-features = false

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[dependencies.zino]
path = "../../zino"
version = "0.20.0"
features = [
    "axum",
    "i18n",
    "jwt",
    "orm",
]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.21.0"
features = [
    "cookie",
    "env-filter",
    "orm-mysql",
    "sentry",
    "validator-email",
    "view-tera",
]

[dependencies.zino-derive]
path = "../../zino-derive"
version = "0.18.0"

[dependencies.zino-model]
path = "../../zino-model"
version = "0.18.0"
