[package]
name = "minimal-app"
description = "A minimal example to run a server."
version = "0.1.0"
rust-version = "1.75"
edition = "2021"
publish = false

[dependencies.zino]
path = "../../zino"
version = "0.19.3"
features = ["axum"]

