[package]
name = "zino-dioxus"
description = "Dioxus components for zino."
version = "0.6.0"
rust-version = "1.75"
edition = "2021"
license = "MIT"
categories = ["gui", "network-programming", "web-programming"]
keywords = ["zino", "dioxus", "components"]
homepage = "https://github.com/zino-rs/zino"
repository = "https://github.com/zino-rs/zino"
documentation = "https://docs.rs/zino-dioxus"
readme = "README.md"

[dependencies]
dioxus = "0.5.1"
dioxus-core = "0.5.1"
dioxus-hooks = "0.5.1"
dioxus-router = "0.5.0"
markdown = "1.0.0-alpha.17"
rust_decimal = "1.35.0"
smallvec = "1.13.2"

[dependencies.chrono]
version = "0.4.38"
features = ["serde"]

[dependencies.dioxus-free-icons]
version = "0.8.5"
features = ["font-awesome-solid"]

[dependencies.tokio]
version = "1.37.0"
features = ["time"]

[dependencies.uuid]
version = "1.8.0"
features = [
    "fast-rng",
    "serde",
    "v4",
    "v7",
]

[dependencies.zino-core]
path = "../zino-core"
version = "0.23.0"
