[package]
name = "actix-app"
description = "An example for actix-web integration."
version = "0.6.2"
rust-version = "1.75"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1.40"

[dependencies.actix-web]
version = "4.5.1"
default-features = false

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[dependencies.zino]
path = "../../zino"
version = "0.18.6"
features = ["actix", "orm"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.19.6"
features = ["orm-postgres", "view-minijinja"]

[dependencies.zino-derive]
path = "../../zino-derive"
version = "0.16.6"

[dependencies.zino-model]
path = "../../zino-model"
version = "0.16.6"
