[package]
name = "actix-app"
description = "An example for actix-web integration."
version = "0.7.3"
rust-version = "1.75"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1.40"

[dependencies.actix-web]
version = "4.5.1"
default-features = false

[dependencies.serde]
version = "1.0.202"
features = ["derive"]

[dependencies.zino]
path = "../../zino"
version = "0.21.5"
features = [
    "actix",
    "i18n",
    "jwt",
    "orm",
]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.22.5"
features = [
    "cookie",
    "env-filter",
    "orm-postgres",
    "view-minijinja",
]

[dependencies.zino-derive]
path = "../../zino-derive"
version = "0.19.5"

[dependencies.zino-model]
path = "../../zino-model"
version = "0.19.5"
